// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvWIuwqNxsk_H28fOTcz4cyWIvk8e0F6o',
    appId: '1:986184003003:web:1a44a055b97903e225a89e',
    messagingSenderId: '986184003003',
    projectId: 'masarak-5f47d',
    authDomain: 'masarak-5f47d.firebaseapp.com',
    storageBucket: 'masarak-5f47d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsLX-DCYIGrlMjfuxKIITy9hpUwkq2IAQ',
    appId: '1:986184003003:android:9e2dccd76fcf291e25a89e',
    messagingSenderId: '986184003003',
    projectId: 'masarak-5f47d',
    storageBucket: 'masarak-5f47d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3S9Uy1chcezFu3coToZ6gBGHy6Gjb15I',
    appId: '1:986184003003:ios:73b79633a58fb69825a89e',
    messagingSenderId: '986184003003',
    projectId: 'masarak-5f47d',
    storageBucket: 'masarak-5f47d.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
