name: Build AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Dependencies
        run: flutter pub get
      
      # 🌟 توليد الأيقونات أولاً قبل أي عملية بناء
      - name: Generate App Icons
        run: flutter pub run flutter_launcher_icons
        
      # بناء ملف AAB للمتجر
      - name: Build AAB
        run: flutter build appbundle --release --android-skip-build-dependency-validation
        
      # بناء ملف APK للهاتف
      - name: Build APK
        run: flutter build apk --release --android-skip-build-dependency-validation

      # رفع ملف APK
      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      
      # رفع ملف AAB
      - name: Upload AAB Release
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/bundle/release/app-release.aab
